FROM node:14

WORKDIR /app

COPY . .

RUN npm install @babel/core --save-dev
RUN npm install @babel/preset-env --save-dev
RUN npm install babel-jest --save-dev
RUN npm install chai --save-dev
RUN npm install cucumber
RUN npm install cucumber-html-reporter
RUN npm install jest
RUN npm install jest-html-reporter
RUN npm jest-puppeteer
RUN npm mocha
RUN npm puppeteer

COPY . .

CMD ["npm", "test", "--"]